# See https://cloud.google.com/cloud-build/docs/build-config
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: gcr.io/k8s-testimages/gcb-docker-gcloud:v20220324-0d59b58358
    id: image-push
    entrypoint: make
    env:
    - PULL_BASE_REF=$_PULL_BASE_REF
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - DOCKER_BUILDKIT=1
    - DOCKER_REGISTRY=$_DOCKER_REGISTRY
    - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
    args:
    - docker-build-push
substitutions:
  _PULL_BASE_REF: 'dev'
  _DOCKER_REGISTRY: 'gcr.io'
  _DOCKER_IMAGE_PREFIX: 'k8s-staging-provider-aws'
timeout: 1200s
