# See https://cloud.google.com/cloud-build/docs/build-config
options:
  dynamic_substitutions: true
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: gcr.io/k8s-testimages/gcb-docker-gcloud
    entrypoint: /buildx-entrypoint
    args:
    - build
    - --tag=gcr.io/$PROJECT_ID/cloud-controller-manager:$_SHORT_TAG
    - --build-arg=VERSION=$_SHORT_TAG
    - --output=type=registry
    - --platform=linux/amd64,linux/arm64
    - .
substitutions:
  _GIT_TAG: 'v99999999-v12345'
  _SHORT_TAG: '${_GIT_TAG:10}'
timeout: 1200s
