---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleName }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ template "cloud-controller-manager.name" . }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.namespace}}
---
