---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.clusterRoleName }}:controller-credentials
  namespace: kube-system
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.clusterRoleName }}:controller-credentials
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
