---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.clusterRoleName }}:controller-credentials
  namespace: kube-system
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  resourceNames:
  - node-controller
  - service-controller
  - route-controller
  - aws-cloud-provider
  - tagging-controller
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - node-controller
  - service-controller
  - route-controller
  - aws-cloud-provider
  - tagging-controller
  verbs:
  - create
