---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBindingName }}
  namespace: {{.Values.namespace}}
  labels: 
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ template "cloud-controller-manager.name" . }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.roleName }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.namespace}}
---
