---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.namespace}}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ template "cloud-controller-manager.name" . }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
---
