name: "Dependency Review"
on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
  workflow_dispatch:
    inputs:
      head_ref:
        description: 'HEAD git reference (tag/branch/commit) to analyze'
        required: true
        default: 'master'
        type: string
      base_ref:
        description: 'Base git reference (tag/branch/commit) to compare against head_ref'
        required: true
        default: 'master'
        type: string
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ inputs.base_ref || github.event.pull_request.base.sha || 'master' }}
          head-ref: ${{ inputs.head_ref || github.event.pull_request.head.sha || github.ref }}
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Setup Go Version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-version-file: go.mod
      - id: govulncheck-tests-e2e
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-version-file: tests/e2e/go.mod
